STAT_ONE_CHOICE_ONE = '01'
STAT_ONE_CHOICE_TWO = '02'
STAT_ONE_CHOICE_THREE = '03'
STAT_ONE_CHOICE_FOUR = '04'
STAT_ONE_CHOICE_FIVE = '11'
STAT_ONE_CHOICE_NOT_SPECIFIED = '99'


STAT_TWO_CHOICE_ONE = '1'
STAT_TWO_CHOICE_TWO = '2'
STAT_TWO_CHOICE_THREE = '3'
STAT_TWO_CHOICE_NOT_SPECIFIED = '9'


